module EMTStudy
using Printf
using SHA
using Serialization
using Unicode
using ..PortableSnapshots
using ..Sources: AnalyticSourceSignal

include(joinpath(@__DIR__, "emt", "source_signal_program.jl"))
include(joinpath(@__DIR__, "emt", "types_and_horizons.jl"))
include(joinpath(@__DIR__, "emt", "nonlinear_network_execution.jl"))
include(joinpath(@__DIR__, "emt", "control_and_machine_boundaries.jl"))
include(joinpath(@__DIR__, "emt", "direct_machine_fleet.jl"))
include(joinpath(@__DIR__, "emt", "deck_context_initialization", "step_context.jl"))
include(joinpath(@__DIR__, "emt", "deck_context_initialization", "harmonic_network.jl"))
include(joinpath(@__DIR__, "emt", "deck_context_initialization", "steady_state_samples.jl"))
include(joinpath(@__DIR__, "emt", "deck_context_initialization", "line_histories.jl"))
include(joinpath(@__DIR__, "emt", "fixed_source_load_flow.jl"))
include(joinpath(@__DIR__, "emt", "fault_equivalent_fitting.jl"))
include(joinpath(@__DIR__, "emt", "line_and_machine_context", "source_and_nonlinear_context.jl"))
include(joinpath(@__DIR__, "emt", "line_and_machine_context", "timestep_execution.jl"))
include(joinpath(@__DIR__, "emt", "line_and_machine_context", "steady_state_and_machines.jl"))
include(joinpath(@__DIR__, "emt", "line_and_machine_context", "transformer_context.jl"))
include(joinpath(@__DIR__, "emt", "dc_simulator_sources.jl"))
include(joinpath(@__DIR__, "emt", "coupled_branch_context.jl"))
include(joinpath(@__DIR__, "emt", "switching_resistor_context.jl"))
include(joinpath(@__DIR__, "emt", "triggered_timed_resistance_context.jl"))
include(joinpath(@__DIR__, "emt", "piecewise_nonlinear_inductor_context.jl"))
include(joinpath(@__DIR__, "emt", "hysteretic_inductor_context.jl"))
include(joinpath(@__DIR__, "emt", "nonlinear_context_and_deck_trace.jl"))
include(joinpath(@__DIR__, "emt", "hybrid_execution.jl"))
include(joinpath(@__DIR__, "emt", "three_phase_vsc.jl"))
include(joinpath(@__DIR__, "emt", "extended_vsc_platform.jl"))
include(joinpath(@__DIR__, "emt", "average_buck_converter.jl"))
include(joinpath(@__DIR__, "emt", "average_boost_converter.jl"))
include(joinpath(@__DIR__, "emt", "average_inverting_buck_boost_converter.jl"))
include(joinpath(@__DIR__, "emt", "average_four_quadrant_converter.jl"))
include(joinpath(@__DIR__, "emt", "switching_chopper_converter.jl"))
include(joinpath(@__DIR__, "emt", "four_quadrant_converter.jl"))
include(joinpath(@__DIR__, "emt", "three_phase_two_level_inverter.jl"))
include(joinpath(@__DIR__, "emt", "three_level_neutral_point_clamped_inverter.jl"))
include(joinpath(@__DIR__, "emt", "flying_capacitor_inverter.jl"))
include(joinpath(@__DIR__, "emt", "cascaded_h_bridge_inverter.jl"))
include(joinpath(@__DIR__, "emt", "matrix_converter.jl"))
include(joinpath(@__DIR__, "emt", "interleaved_chopper_converter.jl"))
include(joinpath(@__DIR__, "emt", "dual_active_bridge_converter.jl"))
include(joinpath(@__DIR__, "emt", "average_dual_active_bridge_converter.jl"))
include(joinpath(@__DIR__, "emt", "line_commutated_rectifier_converter.jl"))
include(joinpath(@__DIR__, "emt", "cycloconverter.jl"))
include(joinpath(@__DIR__, "emt", "converter_applications.jl"))
include(joinpath(@__DIR__, "emt", "converter_system_execution.jl"))
include(joinpath(@__DIR__, "emt", "terminal_state.jl"))
include(joinpath(@__DIR__, "emt", "trace_and_control_inputs.jl"))
include(joinpath(@__DIR__, "emt", "control_expression_execution.jl"))
include(joinpath(@__DIR__, "emt", "control_frequency_initialization.jl"))
include(joinpath(@__DIR__, "emt", "control_device_execution", "control_and_sources.jl"))
include(joinpath(@__DIR__, "emt", "control_device_execution", "deck_control_outputs.jl"))
include(joinpath(@__DIR__, "emt", "control_device_execution", "study_execution.jl"))
include(joinpath(@__DIR__, "emt", "control_device_execution", "report_extraction.jl"))
include(joinpath(@__DIR__, "emt", "ensemble_execution.jl"))
include(joinpath(@__DIR__, "emt", "checkpoint_io.jl"))
include(joinpath(@__DIR__, "emt", "portable_workspace_snapshot.jl"))
include(joinpath(@__DIR__, "emt", "portable_nodal_element_snapshot.jl"))
include(joinpath(@__DIR__, "emt", "portable_control_snapshot.jl"))
include(joinpath(@__DIR__, "emt", "portable_task_scheduler_snapshot.jl"))
include(joinpath(@__DIR__, "emt", "portable_hybrid_snapshot.jl"))
include(joinpath(@__DIR__, "emt", "restart_execution.jl"))
include(joinpath(@__DIR__, "emt", "deck_timestep_orchestration.jl"))
include(joinpath(@__DIR__, "emt", "case_sequence_execution.jl"))
include(joinpath(@__DIR__, "emt", "consistent_initialization", "frequency_and_residuals.jl"))
include(joinpath(@__DIR__, "emt", "consistent_initialization", "state_digest.jl"))
include(joinpath(@__DIR__, "emt", "consistent_initialization", "machine_initialization.jl"))
include(joinpath(@__DIR__, "emt", "consistent_initialization", "converter_and_api.jl"))
include(joinpath(@__DIR__, "emt", "snapshot_results_and_json.jl"))
include(joinpath(@__DIR__, "emt", "result_serialization.jl"))

end
