module ProtectionStudy

using ..StudyCore
using ..StudyInputProfiles
using ..MeasurementChains
using ..EMTTaskPlatform
using ..PortableSnapshots
using SHA

export PROTECTION_STUDY,
       MagnitudeRelayCandidate,
       MagnitudeRelayDecision,
       MagnitudeRelayDirection,
       MagnitudeRelaySettings,
       MagnitudeRelaySnapshot,
       MagnitudeRelayState,
       MagnitudeRelayValueMode,
       AbsoluteMagnitudeValue,
       SignedScalarValue,
       DirectionalRelaySettings,
       DirectionalRelayState,
       DirectionalRelayDecision,
       DirectionalRelaySnapshot,
       evaluate_directional_relay!,
       directional_relay_snapshot,
       restore_directional_relay_snapshot!,
       AbstractDistanceZoneShape,
       MhoDistanceZone,
       PolygonDistanceZone,
       DistanceRelaySettings,
       DistanceRelayState,
       DistanceRelayDecision,
       DistanceRelaySnapshot,
       evaluate_distance_relay!,
       distance_relay_snapshot,
       restore_distance_relay_snapshot!,
       DifferentialRestraintMode,
       HalfSumDifferentialRestraint,
       MaximumDifferentialRestraint,
       DifferentialRelaySettings,
       DifferentialRelayState,
       DifferentialRelayDecision,
       DifferentialRelaySnapshot,
       evaluate_differential_relay!,
       differential_relay_snapshot,
       restore_differential_relay_snapshot!,
       IncrementalWaveDirection,
       ForwardIncrementalWave,
       ReverseIncrementalWave,
       IncrementalWaveSettings,
       IncrementalWaveState,
       IncrementalWaveDecision,
       IncrementalWaveSnapshot,
       evaluate_incremental_wave!,
       incremental_wave_snapshot,
       restore_incremental_wave_snapshot!,
       AbstractProtectionLogicNode,
       ProtectionLogicInputNode,
       ProtectionLogicNotNode,
       ProtectionLogicVoteNode,
       ProtectionLogicLatchNode,
       ProtectionLogicDefinition,
       ProtectionLogicRuntime,
       ProtectionLogicResult,
       ProtectionLogicSnapshot,
       evaluate_protection_logic!,
       protection_logic_snapshot,
       restore_protection_logic_snapshot!,
       ProtectionTaskStage,
       ProtectionMeasurementReleaseStage,
       ProtectionElementEvaluationStage,
       ProtectionLocalLogicStage,
       ProtectionMessageSendStage,
       ProtectionMessageDeliveryStage,
       ProtectionRemoteLogicStage,
       ProtectionTripCommandStage,
       ProtectionTaskOperations,
       ProtectionTaskPipeline,
       ProtectionTaskAdvanceResult,
       protection_task_plan,
       protection_task_operation,
       ProtectionMessageDisposition,
       PassProtectionMessage,
       DropProtectionMessage,
       ProtectionMessageRule,
       ProtectionCommunicationLink,
       QueuedProtectionMessage,
       ProtectionCommunicationRuntime,
       ProtectionCommunicationSnapshot,
       ProtectionMessageSendResult,
       send_protection_message!,
       deliver_due_protection_messages!,
       protection_communication_snapshot,
       restore_protection_communication_snapshot!,
       BreakerPolePosition,
       BreakerPoleOpen,
       BreakerPoleClosed,
       BreakerPoleOpening,
       BreakerPoleClosing,
       BreakerPoleAwaitingCurrentZero,
       EMTBreakerSpecification,
       EMTBreakerPoleRuntime,
       EMTBreakerRuntime,
       EMTBreakerEvent,
       EMTBreakerAdvanceResult,
       EMTBreakerSnapshot,
       EMTBreakerNetworkBinding,
       request_breaker_trip!,
       request_breaker_reclose!,
       advance_emt_breaker!,
       breaker_pole_conductances,
       synchronize_emt_breaker_poles!,
       emt_breaker_snapshot,
       restore_emt_breaker_snapshot!,
       OverMagnitude,
       UnderMagnitude,
       ProtectionDefiniteTimer,
       ProtectionFundamentalPhasorStage,
       ProtectionFrequencyStage,
       ProtectionROCOFStage,
       ProtectionInstantaneousStage,
       ProtectionInverseTimer,
       ProtectionMeasurement,
       ProtectionMeasurementStage,
       ProtectionSequencePhasorStage,
       ProtectionSlidingRMSStage,
       ProtectionTimerMode,
       ProtectionTimerInstantaneous,
       evaluate_magnitude_relay!,
       magnitude_relay_candidate,
       magnitude_relay_signature,
       magnitude_relay_snapshot,
       protection_input_profile,
       protection_measurement,
       ROCOFEstimatorSettings,
       ROCOFEstimatorSnapshot,
       ROCOFEstimatorState,
       estimate_rocof!,
       rocof_estimator_snapshot,
       restore_rocof_estimator_snapshot!,
       restore_magnitude_relay_snapshot!,
       ProtectionProductFamily,
       RadialFeederProtectionProduct,
       DirectionalDistanceLineProtectionProduct,
       TransformerBusDifferentialProtectionProduct,
       MachineConverterFrequencyProtectionProduct,
       DCDifferentialOvercurrentProtectionProduct,
       ProtectionInitializationMode,
       HealthyInactiveProtectionInitialization,
       DeclaredProtectionStateInitialization,
       OperatingPointProtectionInitialization,
       ProtectionTerminalDefinition,
       ProtectionProductSpecification,
       ProtectionProductPreparation,
       ProtectionProductReadiness,
       ProtectionStudyPreparation,
       ProtectionStudyResult,
       ProtectionStudyRefusal,
       ProtectionProductEvent,
       ProtectionProductRuntime,
       ProtectionProductRuntimeSnapshot,
       prepare_protection_product,
       prepare_protection_study,
       protection_product_readiness,
       protection_product_runtime_snapshot,
       restore_protection_product_runtime_snapshot!,
       protection_product_portable_snapshot,
       write_protection_product_portable_snapshot,
       restore_protection_product_portable_snapshot!,
       run_protection

const PROTECTION_STUDY = StudyDescriptor(
    :protection,
    "Protection coordination",
    :protection,
    :planned,
    "src/studies/protection.jl",
)

protection_input_profile() = input_profile(:protection)

include(joinpath(@__DIR__, "protection", "contracts.jl"))
include(joinpath(@__DIR__, "protection", "magnitude_element.jl"))
include(joinpath(@__DIR__, "protection", "frequency_element.jl"))
include(joinpath(@__DIR__, "protection", "phasor_elements.jl"))
include(joinpath(@__DIR__, "protection", "scheme_logic.jl"))
include(joinpath(@__DIR__, "protection", "task_order.jl"))
include(joinpath(@__DIR__, "protection", "breaker_runtime.jl"))
include(joinpath(@__DIR__, "protection", "public_products.jl"))
include(joinpath(@__DIR__, "protection", "portable_products.jl"))

function run_protection(data; kwargs...)
    validate_study_inputs(protection_input_profile(), data)
    study_not_implemented(PROTECTION_STUDY)
end

end
